[rssx]
rss-sync-auto=true
security-key="fa6ee430-ebf6-44f2-a18b-64d691cd2dae"

[sqlite]
path="/var/lib/rssx-api/rssx-api.db"

[mysql]
address="mysql.wiloon.com:3306"

[redis]
address="redis.wiloon.com:32379"

[sync]
# minute
duration=60

[news]
expire-time="-720h"
gc-duration="24h"

[log]
level="debug"
path="/data/rssx/logs/"
file-name="rssx.log"
